server {
    listen 80;

    auth_basic "Natura Shlink";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        proxy_pass http://web_client:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
